/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

class DatabaseManager {
    public void createTable() {
    }

    public void insertRecord() {
    }

    public void insertRecords() {
    }

    public void searchField() {
    }

    public void searchRecord() {
    }
}

interface Command {
    void execute();
}

class CreateTableCommand implements Command {
    public void execute() {
    }
}

class InsertRecordCommand implements Command {
    public void execute() {
    }
}

class SearchFieldCommand implements Command {
    public void execute() {
    }
}

class SearchRecordCommand implements Command {
    public void execute() {
    }
}

class CommandParser {
    public static List<Command> parseCommands(DatabaseManager databaseManager) {
        return null;
    }
}

public class App {
    public static void main(String[] args) {
        DatabaseManager databaseManager = new DatabaseManager();
        List<Command> commands = CommandParser.parseCommands(databaseManager);

        for (Command command : commands) {
            command.execute();
        }
    }
}
